apiVersion: v1
kind: ConfigMap
metadata:
  name: atlassian-exporter-conf
  namespace: exporter
data:
  atlassian_conn_elwillie.json: |-
    {
      "atlassian-site": "willie",
      "atlassian-user": "alias@gmail.com",
      "atlassian-token": "wSCqpbo7OgDXDBMRSjZQAE59"    
    }
  bitbucket_conn_elwillie.json: |-
    {
      "bitbucket-workspace": "willie",
      "bitbucket-user": "willie",
      "bitbucket-token": "ATBBsxRs4jqsAdbsRkjNb7JDZrVv436FE68A"
    }